INSERT INTO STUDENT (NAME, DEPARTMENT, AGE) VALUES ('John Doe', 'CS', 22);
--INSERT INTO STUDENT (NAME, DEPARTMENT, AGE) VALUES ('Max Das', 'BI', 24);
--INSERT INTO STUDENT (NAME, DEPARTMENT, AGE) VALUES ('Sue Storm', 'Engineering', 23);
--INSERT INTO STUDENT (NAME, DEPARTMENT, AGE) VALUES ('Maya Hawke', 'Art', 20);